import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import {
  resolveWikiPaths, PAGE_TYPES, RAW_SUBDIRS,
  readMdFiles, countMdFilesInSubdirs, extractMeta, slugToTitle, type Meta,
} from '../lib/index.js';
import { parseArgs, type Command } from '../../cli.js';

interface Page extends Meta {
  slug: string;
  file: string;
}

type AllPages = Record<string, Page[]>;

async function scanPages(wikiDir: string): Promise<{ allPages: AllPages; totalPages: number }> {
  const allPages: AllPages = {};
  let totalPages = 0;

  for (const { type } of PAGE_TYPES) {
    const dir = join(wikiDir, type);
    const files = await readMdFiles(dir);
    const pages: Page[] = [];
    for (const file of files) {
      if (file === 'index.md') continue;
      const meta = await extractMeta(join(dir, file));
      const slug = file.replace('.md', '');
      pages.push({ slug, file, ...meta, title: meta.title || slugToTitle(slug) });
    }
    allPages[type] = pages;
    totalPages += pages.length;
  }

  return { allPages, totalPages };
}

function renderType(type: string, label: string, pages: Page[]): string[] {
  if (pages.length === 0) return [];
  const lines: string[] = [`### ${label} (${pages.length})`, ''];
  for (const p of pages.sort((a, b) => a.slug.localeCompare(b.slug))) {
    const tag = p.verified === 'no' ? ' ⚠️' : '';
    const yearStr = p.year ? ` (${p.year})` : '';
    lines.push(`- [${p.title}](${type}/${p.file})${yearStr}${tag}`);
  }
  lines.push('');
  return lines;
}

function renderIndex(allPages: AllPages, totalPages: number, rawCount: number): string {
  const lines: string[] = [];
  const now = new Date().toISOString().slice(0, 10);
  const statsLine = PAGE_TYPES
    .filter(({ type }) => allPages[type].length > 0)
    .map(({ type }) => `${allPages[type].length} ${type}`)
    .join(', ');

  lines.push('# Knowledge Base Index');
  lines.push('');
  lines.push(`**Last updated**: ${now}`);
  lines.push(`**Total sources**: ${rawCount}`);
  lines.push(`**Total wiki pages**: ${totalPages}${statsLine ? ` (${statsLine})` : ''}`);
  lines.push('');
  lines.push('> Auto-generated by `cli.cjs generate-index`. Do not edit manually.');
  lines.push('');
  lines.push('---');
  lines.push('');

  lines.push('## Entities');
  lines.push('');
  for (const { type, label, group } of PAGE_TYPES) {
    if (group === 'entity') lines.push(...renderType(type, label, allPages[type]));
  }

  lines.push('## Sources');
  lines.push('');
  for (const { type, label, group } of PAGE_TYPES) {
    if (group === 'source') lines.push(...renderType(type, label, allPages[type]));
  }

  return lines.join('\n');
}

async function generateIndex(wikiDir: string, rawDir: string): Promise<void> {
  console.log('Scanning wiki directory...');

  const { allPages, totalPages } = await scanPages(wikiDir);
  for (const { type, label } of PAGE_TYPES) {
    if (allPages[type].length > 0) console.log(`  ${label}: ${allPages[type].length}`);
  }

  const rawCount = await countMdFilesInSubdirs(rawDir, RAW_SUBDIRS);
  console.log(`  Raw sources: ${rawCount}`);

  const output = renderIndex(allPages, totalPages, rawCount);
  await writeFile(join(wikiDir, 'index.md'), output);
  console.log(`\nGenerated wiki/index.md (${totalPages} pages indexed)`);
}

export const command: Command = {
  description: 'Regenerate wiki/index.md from filesystem. --root DIR',
  run: (args) => {
    const { wikiDir, rawDir } = resolveWikiPaths(parseArgs(args).flags);
    return generateIndex(wikiDir, rawDir);
  },
};
