import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(__dirname, "..");
const sourceDir = path.join(appRoot, "i18n");
const locales = ["en", "zh-CN"];
const checkOnly = process.argv.includes("--check");

function isPlainObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

async function readJson(filePath) {
  return JSON.parse(await readFile(filePath, "utf8"));
}

function compareShape(reference, candidate, currentPath = []) {
  const pointer = currentPath.join(".") || "<root>";

  if (Array.isArray(reference) || Array.isArray(candidate)) {
    if (!Array.isArray(reference) || !Array.isArray(candidate)) {
      throw new Error(`i18n shape mismatch at ${pointer}: array/object mismatch`);
    }
    return;
  }

  if (isPlainObject(reference) || isPlainObject(candidate)) {
    if (!isPlainObject(reference) || !isPlainObject(candidate)) {
      throw new Error(`i18n shape mismatch at ${pointer}: object/value mismatch`);
    }

    const referenceKeys = Object.keys(reference).sort();
    const candidateKeys = Object.keys(candidate).sort();
    if (referenceKeys.join("|") !== candidateKeys.join("|")) {
      throw new Error(
        `i18n key mismatch at ${pointer}: ${referenceKeys.join(", ")} !== ${candidateKeys.join(", ")}`,
      );
    }

    for (const key of referenceKeys) {
      compareShape(reference[key], candidate[key], [...currentPath, key]);
    }
  }
}

function flattenMessages(value, prefix = "", result = {}) {
  if (!isPlainObject(value)) {
    throw new Error(`Expected object while flattening ${prefix || "<root>"}`);
  }

  for (const [key, child] of Object.entries(value)) {
    const nextKey = prefix ? `${prefix}.${key}` : key;
    if (isPlainObject(child)) {
      flattenMessages(child, nextKey, result);
    } else {
      result[nextKey] = child;
    }
  }

  return result;
}

function extractPlaceholders(value) {
  return Array.from(String(value).matchAll(/\{(\w+)\}/g), (match) => match[1]).sort();
}

function comparePlaceholderSets(referenceMessages, candidateMessages, label) {
  for (const key of Object.keys(referenceMessages)) {
    const reference = extractPlaceholders(referenceMessages[key]);
    const candidate = extractPlaceholders(candidateMessages[key]);

    if (reference.join("|") !== candidate.join("|")) {
      throw new Error(
        `i18n placeholder mismatch in ${label}.${key}: ${reference.join(", ")} !== ${candidate.join(", ")}`,
      );
    }
  }
}

function renderTsConst(name, value) {
  return `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;
}

function toRustRawString(value) {
  let hashes = "#";
  while (value.includes(`"${hashes}`)) {
    hashes += "#";
  }
  return `r${hashes}"${value}"${hashes}`;
}

function renderClientModule(dataByLocale) {
  return `// This file is generated by scripts/generate-i18n.mjs. Do not edit manually.

export const SUPPORTED_LOCALES = ${JSON.stringify(locales)} as const;
export type Locale = (typeof SUPPORTED_LOCALES)[number];

${renderTsConst("CLIENT_MESSAGES", Object.fromEntries(locales.map((locale) => [locale, dataByLocale[locale].client.messages])))}
export type MessageKey = keyof typeof CLIENT_MESSAGES.en;

${renderTsConst(
  "CLIENT_RECOMMENDATION_LABELS",
  Object.fromEntries(locales.map((locale) => [locale, dataByLocale[locale].client.recommendationLabels])),
)}
export type RecommendationKey = keyof typeof CLIENT_RECOMMENDATION_LABELS.en;

${renderTsConst(
  "CLIENT_BROWSER_RECOMMENDATIONS",
  Object.fromEntries(locales.map((locale) => [locale, dataByLocale[locale].client.browserRecommendations])),
)}`.trimStart();
}

function renderExtensionModule(dataByLocale) {
  return `// This file is generated by scripts/generate-i18n.mjs. Do not edit manually.

export const SUPPORTED_LOCALES = ${JSON.stringify(locales)} as const;
export type Locale = (typeof SUPPORTED_LOCALES)[number];

${renderTsConst(
  "EXTENSION_RUNTIME_MESSAGES",
  Object.fromEntries(locales.map((locale) => [locale, dataByLocale[locale].extension.runtime])),
)}
export type ExtensionRuntimeKey = keyof typeof EXTENSION_RUNTIME_MESSAGES.en;`.trimStart();
}

function renderRustModule(dataByLocale) {
  const keys = Object.keys(dataByLocale.en.cli);
  const arms = [];

  for (const locale of locales) {
    const localeVariant = locale === "en" ? "Locale::En" : "Locale::ZhCn";
    for (const key of keys) {
      arms.push(
        `        (${localeVariant}, ${JSON.stringify(key)}) => ${toRustRawString(dataByLocale[locale].cli[key])},`,
      );
    }
  }

  return `// This file is generated by scripts/generate-i18n.mjs. Do not edit manually.
use clap::Command;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Locale {
    En,
    ZhCn,
}

pub fn detect_locale_from_args_or_env() -> Locale {
    let args = std::env::args().collect::<Vec<_>>();
    let mut index = 0;
    while index < args.len() {
        if args[index] == "--locale" {
            if let Some(value) = args.get(index + 1) {
                return normalize_locale(value);
            }
        } else if let Some(value) = args[index].strip_prefix("--locale=") {
            return normalize_locale(value);
        }
        index += 1;
    }

    let env_locale = std::env::var("LEARNWY_LOCALE")
        .ok()
        .or_else(|| std::env::var("LC_ALL").ok())
        .or_else(|| std::env::var("LANG").ok());

    normalize_locale(env_locale.as_deref().unwrap_or("en"))
}

pub fn normalize_locale(value: &str) -> Locale {
    if value.to_lowercase().starts_with("zh") {
        Locale::ZhCn
    } else {
        Locale::En
    }
}

pub fn localize_command(command: Command, locale: Locale) -> Command {
    command
        .about(message(locale, "cli.about"))
        .long_about(message(locale, "cli.about"))
        .mut_arg("locale", |argument| {
            argument
                .help(message(locale, "arg.locale.help"))
                .long_help(message(locale, "arg.locale.help"))
        })
        .mut_subcommand("healthcheck", |subcommand| {
            subcommand.about(message(locale, "command.healthcheck.about"))
        })
        .mut_subcommand("workspace-summary", |subcommand| {
            subcommand.about(message(locale, "command.workspace_summary.about"))
        })
        .mut_subcommand("list", |subcommand| {
            subcommand.about(message(locale, "command.list.about"))
        })
        .mut_subcommand("stats", |subcommand| {
            subcommand.about(message(locale, "command.stats.about"))
        })
        .mut_subcommand("recommend-visualization", |subcommand| {
            subcommand.about(message(locale, "command.recommend.about"))
        })
        .mut_subcommand("inspect", |subcommand| {
            subcommand
                .about(message(locale, "command.inspect.about"))
                .mut_arg("file", |argument| argument.help(message(locale, "arg.file.help")))
        })
        .mut_subcommand("create", |subcommand| {
            subcommand
                .about(message(locale, "command.create.about"))
                .mut_arg("title", |argument| argument.help(message(locale, "arg.title.help")))
                .mut_arg("summary", |argument| argument.help(message(locale, "arg.summary.help")))
                .mut_arg("groups", |argument| argument.help(message(locale, "arg.groups.help")))
                .mut_arg("tags", |argument| argument.help(message(locale, "arg.tags.help")))
                .mut_arg("targets", |argument| argument.help(message(locale, "arg.targets.help")))
        })
}

fn message(locale: Locale, key: &str) -> &'static str {
    match (locale, key) {
${arms.join("\n")}
        _ => "",
    }
}

#[cfg(test)]
mod tests {
    use super::{message, normalize_locale, Locale};

    #[test]
    fn normalizes_zh_locale_variants() {
        assert_eq!(normalize_locale("zh"), Locale::ZhCn);
        assert_eq!(normalize_locale("zh-CN"), Locale::ZhCn);
        assert_eq!(normalize_locale("zh_Hans"), Locale::ZhCn);
    }

    #[test]
    fn falls_back_to_english_for_other_locales() {
        assert_eq!(normalize_locale("en-US"), Locale::En);
        assert_eq!(normalize_locale("ja"), Locale::En);
    }

    #[test]
    fn exposes_generated_messages() {
        assert!(!message(Locale::En, "cli.about").is_empty());
        assert!(!message(Locale::ZhCn, "cli.about").is_empty());
        assert!(!message(Locale::En, "command.list.about").is_empty());
    }
}`.trimStart();
}

async function writeOutput(filePath, content) {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content);
}

async function main() {
  const dataByLocale = Object.fromEntries(
    await Promise.all(
      locales.map(async (locale) => [locale, await readJson(path.join(sourceDir, `${locale}.json`))]),
    ),
  );

  compareShape(dataByLocale.en, dataByLocale["zh-CN"]);

  const flattenedClient = Object.fromEntries(
    locales.map((locale) => [
      locale,
      {
        ...dataByLocale[locale],
        client: {
          ...dataByLocale[locale].client,
          messages: flattenMessages(dataByLocale[locale].client.messages),
        },
      },
    ]),
  );

  compareShape(flattenedClient.en.client.messages, flattenedClient["zh-CN"].client.messages);
  compareShape(flattenedClient.en.cli, flattenedClient["zh-CN"].cli);
  compareShape(flattenedClient.en.extension.package, flattenedClient["zh-CN"].extension.package);
  compareShape(flattenedClient.en.extension.runtime, flattenedClient["zh-CN"].extension.runtime);
  comparePlaceholderSets(
    flattenedClient.en.client.messages,
    flattenedClient["zh-CN"].client.messages,
    "client.messages",
  );
  comparePlaceholderSets(flattenedClient.en.cli, flattenedClient["zh-CN"].cli, "cli");
  comparePlaceholderSets(
    flattenedClient.en.extension.runtime,
    flattenedClient["zh-CN"].extension.runtime,
    "extension.runtime",
  );

  const outputs = [
    [
      path.join(appRoot, "client", "src", "lib", "generated-i18n.ts"),
      renderClientModule(flattenedClient),
    ],
    [
      path.join(appRoot, "extension", "src", "generated-i18n.ts"),
      renderExtensionModule(flattenedClient),
    ],
    [
      path.join(appRoot, "extension", "package.nls.json"),
      `${JSON.stringify(flattenedClient.en.extension.package, null, 2)}\n`,
    ],
    [
      path.join(appRoot, "extension", "package.nls.zh-cn.json"),
      `${JSON.stringify(flattenedClient["zh-CN"].extension.package, null, 2)}\n`,
    ],
    [
      path.join(appRoot, "cli", "crates", "rule-cli", "src", "generated_i18n.rs"),
      renderRustModule(flattenedClient),
    ],
  ];

  if (checkOnly) {
    for (const [filePath, nextContent] of outputs) {
      const currentContent = await readFile(filePath, "utf8").catch(() => null);
      if (currentContent !== nextContent) {
        throw new Error(`Generated i18n output is stale: ${path.relative(appRoot, filePath)}`);
      }
    }
    return;
  }

  for (const [filePath, content] of outputs) {
    await writeOutput(filePath, content);
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
