// This file is generated by scripts/generate-i18n.mjs. Do not edit manually.
use clap::Command;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Locale {
    En,
    ZhCn,
}

pub fn detect_locale_from_args_or_env() -> Locale {
    let args = std::env::args().collect::<Vec<_>>();
    let mut index = 0;
    while index < args.len() {
        if args[index] == "--locale" {
            if let Some(value) = args.get(index + 1) {
                return normalize_locale(value);
            }
        } else if let Some(value) = args[index].strip_prefix("--locale=") {
            return normalize_locale(value);
        }
        index += 1;
    }

    let env_locale = std::env::var("LEARNWY_LOCALE")
        .ok()
        .or_else(|| std::env::var("LC_ALL").ok())
        .or_else(|| std::env::var("LANG").ok());

    normalize_locale(env_locale.as_deref().unwrap_or("en"))
}

pub fn normalize_locale(value: &str) -> Locale {
    if value.to_lowercase().starts_with("zh") {
        Locale::ZhCn
    } else {
        Locale::En
    }
}

pub fn localize_command(command: Command, locale: Locale) -> Command {
    command
        .about(message(locale, "cli.about"))
        .long_about(message(locale, "cli.about"))
        .mut_arg("locale", |argument| {
            argument
                .help(message(locale, "arg.locale.help"))
                .long_help(message(locale, "arg.locale.help"))
        })
        .mut_subcommand("healthcheck", |subcommand| {
            subcommand.about(message(locale, "command.healthcheck.about"))
        })
        .mut_subcommand("workspace-summary", |subcommand| {
            subcommand.about(message(locale, "command.workspace_summary.about"))
        })
        .mut_subcommand("list", |subcommand| {
            subcommand.about(message(locale, "command.list.about"))
        })
        .mut_subcommand("stats", |subcommand| {
            subcommand.about(message(locale, "command.stats.about"))
        })
        .mut_subcommand("recommend-visualization", |subcommand| {
            subcommand.about(message(locale, "command.recommend.about"))
        })
        .mut_subcommand("inspect", |subcommand| {
            subcommand
                .about(message(locale, "command.inspect.about"))
                .mut_arg("file", |argument| argument.help(message(locale, "arg.file.help")))
        })
        .mut_subcommand("create", |subcommand| {
            subcommand
                .about(message(locale, "command.create.about"))
                .mut_arg("title", |argument| argument.help(message(locale, "arg.title.help")))
                .mut_arg("summary", |argument| argument.help(message(locale, "arg.summary.help")))
                .mut_arg("groups", |argument| argument.help(message(locale, "arg.groups.help")))
                .mut_arg("tags", |argument| argument.help(message(locale, "arg.tags.help")))
                .mut_arg("targets", |argument| argument.help(message(locale, "arg.targets.help")))
        })
}

fn message(locale: Locale, key: &str) -> &'static str {
    match (locale, key) {
        (Locale::En, "cli.about") => r#"CLI for the intelligent rule manager workspace"#,
        (Locale::En, "arg.locale.help") => r#"Choose the CLI locale, for example en or zh-CN"#,
        (Locale::En, "command.healthcheck.about") => r#"Print the shared rule-core healthcheck as JSON"#,
        (Locale::En, "command.workspace_summary.about") => r#"Print the current shared rules workspace summary as JSON"#,
        (Locale::En, "command.list.about") => r#"List discovered rules as JSON"#,
        (Locale::En, "command.stats.about") => r#"Print rule library statistics as JSON"#,
        (Locale::En, "command.recommend.about") => r#"Print the current visualization recommendation as JSON"#,
        (Locale::En, "command.inspect.about") => r#"Inspect one rule document as JSON"#,
        (Locale::En, "command.create.about") => r#"Create one rule document and print it as JSON"#,
        (Locale::En, "arg.file.help") => r#"Path to the rule Markdown file"#,
        (Locale::En, "arg.title.help") => r#"Rule title"#,
        (Locale::En, "arg.summary.help") => r#"Optional one-line summary"#,
        (Locale::En, "arg.groups.help") => r#"Comma-separated groups"#,
        (Locale::En, "arg.tags.help") => r#"Comma-separated tags"#,
        (Locale::En, "arg.targets.help") => r#"Comma-separated targets"#,
        (Locale::ZhCn, "cli.about") => r#"智能规则管理器工作区 CLI"#,
        (Locale::ZhCn, "arg.locale.help") => r#"选择 CLI 语言，例如 en 或 zh-CN"#,
        (Locale::ZhCn, "command.healthcheck.about") => r#"以 JSON 输出共享 rule-core 健康检查结果"#,
        (Locale::ZhCn, "command.workspace_summary.about") => r#"以 JSON 输出当前共享规则工作区摘要"#,
        (Locale::ZhCn, "command.list.about") => r#"以 JSON 列出已发现的规则"#,
        (Locale::ZhCn, "command.stats.about") => r#"以 JSON 输出规则库统计信息"#,
        (Locale::ZhCn, "command.recommend.about") => r#"以 JSON 输出当前可视化建议"#,
        (Locale::ZhCn, "command.inspect.about") => r#"以 JSON 查看单条规则文档"#,
        (Locale::ZhCn, "command.create.about") => r#"创建一条规则文档并以 JSON 输出"#,
        (Locale::ZhCn, "arg.file.help") => r#"规则 Markdown 文件路径"#,
        (Locale::ZhCn, "arg.title.help") => r#"规则标题"#,
        (Locale::ZhCn, "arg.summary.help") => r#"可选的一行摘要"#,
        (Locale::ZhCn, "arg.groups.help") => r#"逗号分隔的分组列表"#,
        (Locale::ZhCn, "arg.tags.help") => r#"逗号分隔的标签列表"#,
        (Locale::ZhCn, "arg.targets.help") => r#"逗号分隔的目标列表"#,
        _ => "",
    }
}

#[cfg(test)]
mod tests {
    use super::{message, normalize_locale, Locale};

    #[test]
    fn normalizes_zh_locale_variants() {
        assert_eq!(normalize_locale("zh"), Locale::ZhCn);
        assert_eq!(normalize_locale("zh-CN"), Locale::ZhCn);
        assert_eq!(normalize_locale("zh_Hans"), Locale::ZhCn);
    }

    #[test]
    fn falls_back_to_english_for_other_locales() {
        assert_eq!(normalize_locale("en-US"), Locale::En);
        assert_eq!(normalize_locale("ja"), Locale::En);
    }

    #[test]
    fn exposes_generated_messages() {
        assert!(!message(Locale::En, "cli.about").is_empty());
        assert!(!message(Locale::ZhCn, "cli.about").is_empty());
        assert!(!message(Locale::En, "command.list.about").is_empty());
    }
}