// This file is generated by scripts/generate-i18n.mjs. Do not edit manually.

export const SUPPORTED_LOCALES = ["en","zh-CN"] as const;
export type Locale = (typeof SUPPORTED_LOCALES)[number];

export const EXTENSION_RUNTIME_MESSAGES = {
  "en": {
    "channel.name": "Intelligent Rule Manager",
    "output.workspaceSummary": "Workspace summary",
    "info.rulesRoot": "Rules root: {path}",
    "output.ruleDetail": "Rule detail: {title}",
    "input.create.title.placeholder": "TypeScript Import Hygiene",
    "input.create.title.prompt": "Enter the new rule title",
    "input.create.summary.placeholder": "One sentence explaining the purpose of the rule.",
    "input.create.summary.prompt": "Enter an optional summary",
    "field.groups.label": "Groups",
    "field.groups.placeholder": "shared, frontend",
    "field.tags.label": "Tags",
    "field.tags.placeholder": "typescript, imports",
    "field.targets.label": "Targets",
    "field.targets.placeholder": "agents-md, trae-rule",
    "info.createdRule": "Created rule: {title}",
    "output.ruleLibraryStats": "Rule library stats",
    "info.statsSummary": "{count} rules, {tagCount} tags, {groupCount} groups",
    "output.visualizationRecommendation": "Visualization recommendation",
    "info.recommendationSummary": "Recommendation: {recommendation} (score {score})",
    "info.noRulesFound": "No rules were found.",
    "quickPick.selectRule": "Select a rule",
    "input.csv.prompt": "Enter {label} as a comma-separated list",
    "error.unknownCargoCommand": "Unknown cargo command error"
  },
  "zh-CN": {
    "channel.name": "智能规则管理器",
    "output.workspaceSummary": "工作区摘要",
    "info.rulesRoot": "规则根目录：{path}",
    "output.ruleDetail": "规则详情：{title}",
    "input.create.title.placeholder": "TypeScript Import Hygiene",
    "input.create.title.prompt": "输入新规则标题",
    "input.create.summary.placeholder": "用一句话说明这条规则的作用。",
    "input.create.summary.prompt": "输入可选摘要",
    "field.groups.label": "分组",
    "field.groups.placeholder": "shared, frontend",
    "field.tags.label": "标签",
    "field.tags.placeholder": "typescript, imports",
    "field.targets.label": "目标",
    "field.targets.placeholder": "agents-md, trae-rule",
    "info.createdRule": "已创建规则：{title}",
    "output.ruleLibraryStats": "规则库统计",
    "info.statsSummary": "{count} 条规则，{tagCount} 个标签，{groupCount} 个分组",
    "output.visualizationRecommendation": "可视化建议",
    "info.recommendationSummary": "建议：{recommendation}（分数 {score}）",
    "info.noRulesFound": "没有找到任何规则。",
    "quickPick.selectRule": "选择一条规则",
    "input.csv.prompt": "请输入 {label}，使用逗号分隔",
    "error.unknownCargoCommand": "未知的 cargo 命令错误"
  }
} as const;

export type ExtensionRuntimeKey = keyof typeof EXTENSION_RUNTIME_MESSAGES.en;