#!/usr/bin/env node
import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import {
  WIKI_DIR, RAW_DIR, PAGE_TYPES, RAW_SUBDIRS,
  readMdFiles, readMdFilesDeep, countMdFilesInSubdirs, extractMeta, slugToTitle,
  CATEGORY_ORDER, categorize
} from '../shared/index.mjs'

const DEEP_SCAN_TYPES = new Set(['concepts'])

async function scanPages() {
  const allPages = {}
  let totalPages = 0

  for (const { type } of PAGE_TYPES) {
    const dir = join(WIKI_DIR, type)
    const pages = []

    if (DEEP_SCAN_TYPES.has(type)) {
      const entries = await readMdFilesDeep(dir)
      for (const { file, subdir } of entries) {
        const relPath = subdir ? `${subdir}/${file}` : file
        const meta = await extractMeta(join(dir, relPath))
        const slug = file.replace('.md', '')
        pages.push({
          slug,
          file,
          relPath,
          subdir,
          ...meta,
          title: meta.title || slugToTitle(slug)
        })
      }
    } else {
      const files = await readMdFiles(dir)
      for (const file of files) {
        const meta = await extractMeta(join(dir, file))
        const slug = file.replace('.md', '')
        pages.push({
          slug,
          file,
          relPath: file,
          subdir: '',
          ...meta,
          title: meta.title || slugToTitle(slug)
        })
      }
    }

    allPages[type] = pages
    totalPages += pages.length
  }

  return { allPages, totalPages }
}

function groupByDiscipline(allPages) {
  const groups = {}

  for (const [type, pages] of Object.entries(allPages)) {
    for (const page of pages) {
      const disc = page.discipline || page.platform || 'Uncategorized'
      if (!groups[disc]) groups[disc] = {}
      if (!groups[disc][type]) groups[disc][type] = []
      groups[disc][type].push(page)
    }
  }

  return groups
}

function organizeByCategory(disciplineGroups) {
  const organized = {}

  for (const [disc, types] of Object.entries(disciplineGroups)) {
    const cat = categorize(disc)
    if (!organized[cat]) organized[cat] = { disciplines: {} }
    if (!organized[cat].disciplines[disc]) organized[cat].disciplines[disc] = {}

    for (const [type, pages] of Object.entries(types)) {
      if (!organized[cat].disciplines[disc][type]) organized[cat].disciplines[disc][type] = []
      organized[cat].disciplines[disc][type].push(...pages)
    }
  }

  return organized
}

function renderSection(types) {
  const lines = []
  const { summaries = [], concepts = [], snippets = [], troubleshooting: troubles = [], comparisons = [] } = types

  for (const s of summaries) {
    const yearStr = s.year ? ` (${s.year})` : ''
    lines.push(`- [${s.title}](summaries/${s.relPath})${yearStr}`)
  }
  for (const c of concepts) {
    const tag = c.verified === 'no' ? ' ⚠️' : ''
    lines.push(`  - [${c.title}](concepts/${c.relPath})${tag}`)
  }
  if (snippets.length > 0) {
    lines.push('  - **Snippets**:')
    for (const sn of snippets) lines.push(`    - [${sn.title}](snippets/${sn.relPath})`)
  }
  if (troubles.length > 0) {
    lines.push('  - **Troubleshooting**:')
    for (const t of troubles) lines.push(`    - [${t.title}](troubleshooting/${t.relPath})`)
  }
  for (const comp of comparisons) {
    lines.push(`  - [${comp.title}](comparisons/${comp.relPath})`)
  }

  return lines
}

function renderIndex({ allPages, totalPages, rawCount, organized }) {
  const lines = []
  const now = new Date().toISOString().slice(0, 10)
  const statsLine = Object.entries(allPages)
    .filter(([, p]) => p.length > 0)
    .map(([type, p]) => `${p.length} ${type}`)
    .join(', ')

  lines.push('# Knowledge Base Index')
  lines.push('')
  lines.push('**Created**: 2026-04-26')
  lines.push(`**Last updated**: ${now}`)
  lines.push(`**Total sources**: ${rawCount}`)
  lines.push(`**Total wiki pages**: ${totalPages} (${statsLine})`)
  lines.push('')
  lines.push('> This file is auto-generated by `scripts/generate-index`. Do not edit manually.')
  lines.push('')
  lines.push('---')
  lines.push('')
  lines.push('## By Category')
  lines.push('')

  for (const { category } of CATEGORY_ORDER) {
    const catData = organized[category]
    if (!catData) continue

    let catSummaries = 0
    let catConcepts = 0
    let catSnippets = 0
    let catTrouble = 0
    let catComps = 0

    for (const types of Object.values(catData.disciplines)) {
      catSummaries += (types.summaries || []).length
      catConcepts += (types.concepts || []).length
      catSnippets += (types.snippets || []).length
      catTrouble += (types.troubleshooting || []).length
      catComps += (types.comparisons || []).length
    }

    const parts = []
    if (catSummaries) parts.push(`${catSummaries} books/articles`)
    if (catConcepts) parts.push(`${catConcepts} concepts`)
    if (catSnippets) parts.push(`${catSnippets} snippets`)
    if (catTrouble) parts.push(`${catTrouble} troubleshooting`)
    if (catComps) parts.push(`${catComps} comparisons`)

    lines.push(`### ${category} (${parts.join(', ')})`)
    lines.push('')

    for (const types of Object.values(catData.disciplines)) {
      lines.push(...renderSection(types))
    }

    lines.push('')
  }

  if (organized['Other']) {
    lines.push('### Other')
    lines.push('')
    for (const types of Object.values(organized['Other'].disciplines)) {
      lines.push(...renderSection(types))
    }
    lines.push('')
  }

  lines.push('## Entities')
  lines.push('')
  for (const e of (allPages.entities || [])) {
    lines.push(`- [${e.title}](entities/${e.relPath})`)
  }
  lines.push('')

  return lines.join('\n')
}

async function run() {
  console.log('Scanning wiki directory...')

  const { allPages, totalPages } = await scanPages()

  for (const { type, label } of PAGE_TYPES) {
    console.log(`  ${label}: ${allPages[type].length}`)
  }

  const rawCount = await countMdFilesInSubdirs(RAW_DIR, RAW_SUBDIRS)
  console.log(`  Raw sources: ${rawCount}`)

  const disciplineGroups = groupByDiscipline(allPages)
  const organized = organizeByCategory(disciplineGroups)
  const output = renderIndex({ allPages, totalPages, rawCount, organized })

  const outPath = join(WIKI_DIR, 'index.md')
  await writeFile(outPath, output)
  console.log(`\nGenerated wiki/index.md (${totalPages} pages indexed)`)
}

run().catch(err => {
  console.error('generate-index failed:', err.message)
  process.exit(1)
})
